const STORAGE='athleticoVisualAdminV3';
const PAGES=[['index.html','Αρχική'],['services.html','Υπηρεσίες'],['team.html','Η ομάδα'],['experiences.html','Εμπειρίες'],['contact.html','Επικοινωνία']];
let state={pages:{},design:{accent:'#d4af37',contentWidth:1300}};try{state={...state,...JSON.parse(localStorage.getItem(STORAGE)||'{}')}}catch{}
state.pages=state.pages||{};state.design=state.design||{accent:'#d4af37',contentWidth:1300};
let current='index.html',selected=null,currentTab='content',history=[];
const iframe=document.getElementById('preview'),stage=document.getElementById('stage'),status=document.getElementById('status'),selectedBox=document.getElementById('selected'),inspector=document.getElementById('inspector');
const esc=s=>(window.CSS&&CSS.escape)?CSS.escape(s):String(s).replace(/[^a-zA-Z0-9_-]/g,'\\$&');
const px=(v,f=0)=>Number.isFinite(parseFloat(v))?parseFloat(v):f;
const hex=rgb=>{if(!rgb||rgb==='transparent'||rgb.includes('rgba(0, 0, 0, 0)'))return'#000000';const m=rgb.match(/\d+/g);return(!m||m.length<3)?'#ffffff':'#'+m.slice(0,3).map(n=>(+n).toString(16).padStart(2,'0')).join('')};
function pageState(){return state.pages[current]||(state.pages[current]={elements:{},page:{}})}
function snapshot(){history.push(JSON.stringify(state));if(history.length>50)history.shift()}
function persist(msg='Αποθηκεύτηκε'){localStorage.setItem(STORAGE,JSON.stringify(state));status.textContent=msg}
function selectorFor(el){if(el.id)return'#'+esc(el.id);const attr=['data-content-key','data-image-key','data-service','data-section'].find(a=>el.hasAttribute?.(a));if(attr)return`[${attr}="${el.getAttribute(attr)}"]`;const parts=[];while(el&&el.nodeType===1&&el!==el.ownerDocument.body){let s=el.tagName.toLowerCase();const cls=[...el.classList].filter(c=>!c.startsWith('admin-')&&!c.startsWith('is-')).slice(0,2);if(cls.length)s+='.'+cls.map(esc).join('.');const p=el.parentElement;if(p){const same=[...p.children].filter(x=>x.tagName===el.tagName);if(same.length>1)s+=`:nth-of-type(${same.indexOf(el)+1})`}parts.unshift(s);el=p;if(parts.length>=6)break}return parts.join(' > ')}
function ensureOverride(sel){const ps=pageState();return ps.elements[sel]||(ps.elements[sel]={style:{}})}
function applySaved(){const doc=iframe.contentDocument;if(!doc)return;const ps=pageState();Object.entries(ps.elements||{}).forEach(([sel,o])=>{let el;try{el=doc.querySelector(sel)}catch{}if(!el)return;if(o.text!==undefined)el.textContent=o.text;if(o.html!==undefined)el.innerHTML=o.html;if(o.src&&el.tagName==='IMG')el.src=o.src;Object.entries(o.style||{}).forEach(([k,v])=>el.style.setProperty(k.replace(/[A-Z]/g,m=>'-'+m.toLowerCase()),v,'important'))});if(ps.page?.background)doc.body.style.setProperty('background',ps.page.background,'important');if(ps.page?.color)doc.body.style.setProperty('color',ps.page.color,'important');doc.documentElement.style.setProperty('--admin-accent',state.design.accent||'#d4af37')}
function pagesUI(){const box=document.getElementById('pages');box.innerHTML='';PAGES.forEach(([f,l])=>{const b=document.createElement('button');b.textContent=l;b.className=f===current?'active':'';b.onclick=()=>loadPage(f,l);box.appendChild(b)})}
function buildSections(){const box=document.getElementById('sections');box.innerHTML='';const doc=iframe.contentDocument;if(!doc)return;const candidates=[...doc.querySelectorAll('body > header, body > main > section, body > section, body > footer, main > header')].filter((el,i,a)=>a.indexOf(el)===i);if(!candidates.length)candidates.push(doc.body);candidates.forEach((el,i)=>{const b=document.createElement('button');const raw=(el.id||el.className||el.tagName).toString().replace(/\s+/g,' ').trim();let name='Section '+(i+1);if(el.tagName==='HEADER'&&i===0)name='Header / Menu';else if(/hero/i.test(raw))name='Hero';else if(el.tagName==='FOOTER')name='Footer';else if(raw)name='Section '+(i+1)+' · '+raw.split(' ')[0].replace(/[.#_-]/g,' ');b.innerHTML=`<span>${name}</span><small>${String(i+1).padStart(2,'0')}</small>`;b.onclick=()=>{selectElement(el,'style');el.scrollIntoView({behavior:'smooth',block:'center'});[...box.children].forEach(x=>x.classList.remove('active'));b.classList.add('active')};box.appendChild(b)})}
function loadPage(f,label){current=f;selected=null;selectedBox.textContent='Δεν έχει επιλεγεί στοιχείο.';inspector.innerHTML='<div class="empty">Πάτησε σε κείμενο, φωτογραφία ή section μέσα στο preview.</div>';document.getElementById('previewPageLabel').textContent=label||PAGES.find(x=>x[0]===f)?.[1]||f;iframe.src='../'+f+'?admin-preview=1&t='+Date.now();pagesUI()}
function attachEditor(){const doc=iframe.contentDocument;if(!doc)return;applySaved();buildSections();const q='h1,h2,h3,h4,h5,h6,p,span,strong,em,a,button,img,section,article,div,header,footer,li,label,input,textarea';doc.querySelectorAll(q).forEach(el=>{if(el.closest('script,style'))return;el.addEventListener('click',e=>{if(el.tagName==='A'||el.tagName==='BUTTON')e.preventDefault();e.stopPropagation();const tab=el.tagName==='IMG'?'image':(['SECTION','ARTICLE','DIV','HEADER','FOOTER'].includes(el.tagName)?'style':'content');selectElement(el,tab)},true)});status.textContent='Live preview έτοιμο'}
function selectElement(el,tab=currentTab){const doc=iframe.contentDocument;doc.querySelectorAll('[data-admin-v3-selected]').forEach(x=>{x.style.outline=x.dataset.adminOldOutline||'';x.style.outlineOffset=x.dataset.adminOldOffset||'';delete x.dataset.adminV3Selected});el.dataset.adminOldOutline=el.style.outline||'';el.dataset.adminOldOffset=el.style.outlineOffset||'';el.dataset.adminV3Selected='1';el.style.outline='2px solid #d4af37';el.style.outlineOffset='3px';selected={el,selector:selectorFor(el)};currentTab=tab;selectedBox.textContent=`${el.tagName} · ${selected.selector}`;tabsUI();renderInspector()}
function tabsUI(){document.querySelectorAll('#tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===currentTab))}
document.querySelectorAll('#tabs button').forEach(b=>b.onclick=()=>{currentTab=b.dataset.tab;tabsUI();renderInspector()});
function setStyle(prop,val){if(!selected)return;snapshot();selected.el.style.setProperty(prop.replace(/[A-Z]/g,m=>'-'+m.toLowerCase()),val,'important');ensureOverride(selected.selector).style[prop]=val;persist('Live αλλαγή')}
function bind(id,prop,suffix=''){const el=document.getElementById(id);if(el)el.oninput=e=>setStyle(prop,e.target.value+suffix)}
function option(v,l=v){return`<option value="${v}">${l}</option>`}
function renderInspector(){if(!selected)return;const {el}=selected;if(currentTab==='image')return imageInspector();if(currentTab==='style')return styleInspector();if(currentTab==='spacing')return spacingInspector();if(currentTab==='advanced')return advancedInspector();return contentInspector()}
function contentInspector(){const {el,selector}=selected;if(el.tagName==='IMG'){currentTab='image';tabsUI();return imageInspector()}const cs=iframe.contentWindow.getComputedStyle(el);inspector.innerHTML=`<div class="subhead">Περιεχόμενο</div><label>Κείμενο<textarea id="textValue"></textarea></label><div class="grid2"><label>Γραμματοσειρά<select id="fontFamily">${option("'Cormorant Garamond',serif",'Cormorant Garamond')}${option("Inter,Arial,sans-serif",'Inter')}${option('Georgia,serif','Georgia')}${option('Arial,sans-serif','Arial')}${option("'Times New Roman',serif",'Times New Roman')}</select></label><label>Μέγεθος px<input id="fontSize" type="number" min="6" max="200" value="${px(cs.fontSize,16)}"></label><label>Πάχος<select id="fontWeight">${[200,300,400,500,600,700,800,900].map(v=>option(v)).join('')}</select></label><label>Χρώμα<input id="textColor" type="color" value="${hex(cs.color)}"></label><label>Στοίχιση<select id="textAlign">${['left','center','right','justify'].map(v=>option(v,v)).join('')}</select></label><label>Style<select id="fontStyle">${option('normal','Κανονικό')}${option('italic','Πλάγιο')}</select></label></div>`;document.getElementById('textValue').value=el.innerText||el.textContent||'';document.getElementById('textValue').oninput=e=>{snapshot();el.textContent=e.target.value;ensureOverride(selector).text=e.target.value;persist('Κείμενο live')};bind('fontSize','fontSize','px');document.getElementById('fontFamily').onchange=e=>setStyle('fontFamily',e.target.value);document.getElementById('fontWeight').onchange=e=>setStyle('fontWeight',e.target.value);document.getElementById('textColor').oninput=e=>setStyle('color',e.target.value);document.getElementById('textAlign').onchange=e=>setStyle('textAlign',e.target.value);document.getElementById('fontStyle').onchange=e=>setStyle('fontStyle',e.target.value)}
function styleInspector(){const cs=iframe.contentWindow.getComputedStyle(selected.el);inspector.innerHTML=`<div class="subhead">Χρώμα & φόντο</div><div class="grid2"><label>Χρώμα κειμένου<input id="color" type="color" value="${hex(cs.color)}"></label><label>Φόντο<input id="bg" type="color" value="${hex(cs.backgroundColor)}"></label><label>Opacity %<input id="opacity" type="number" min="0" max="100" value="${Math.round(px(cs.opacity,1)*100)}"></label><label>Radius px<input id="radius" type="number" min="0" max="200" value="${px(cs.borderRadius,0)}"></label></div><div class="subhead">Τυπογραφία</div><div class="grid2"><label>Μέγεθος px<input id="fs2" type="number" min="6" max="200" value="${px(cs.fontSize,16)}"></label><label>Line height<input id="lh" type="number" min=".6" max="4" step=".05" value="${(px(cs.lineHeight,px(cs.fontSize,16)*1.2)/px(cs.fontSize,16)).toFixed(2)}"></label><label>Letter spacing px<input id="ls" type="number" step=".1" value="${px(cs.letterSpacing,0)}"></label><label>Text transform<select id="transform">${option('none','Κανονικό')}${option('uppercase','ΚΕΦΑΛΑΙΑ')}${option('lowercase','πεζά')}${option('capitalize','Κάθε Λέξη')}</select></label></div><div class="subhead">Border</div><div class="grid2"><label>Πάχος px<input id="borderWidth" type="number" min="0" max="20" value="${px(cs.borderTopWidth,0)}"></label><label>Χρώμα<input id="borderColor" type="color" value="${hex(cs.borderTopColor)}"></label></div>`;document.getElementById('color').oninput=e=>setStyle('color',e.target.value);document.getElementById('bg').oninput=e=>setStyle('backgroundColor',e.target.value);document.getElementById('opacity').oninput=e=>setStyle('opacity',(e.target.value/100).toString());bind('radius','borderRadius','px');bind('fs2','fontSize','px');bind('lh','lineHeight');bind('ls','letterSpacing','px');document.getElementById('transform').onchange=e=>setStyle('textTransform',e.target.value);bind('borderWidth','borderWidth','px');document.getElementById('borderColor').oninput=e=>setStyle('borderColor',e.target.value);setTimeout(()=>{document.getElementById('transform').value=cs.textTransform||'none'},0)}
function spacingInspector(){const cs=iframe.contentWindow.getComputedStyle(selected.el);inspector.innerHTML=`<div class="subhead">Μέγεθος</div><div class="grid2"><label>Width<input id="width" value="${cs.width}"></label><label>Height<input id="height" value="${cs.height}"></label><label>Max width<input id="maxWidth" value="${cs.maxWidth}"></label><label>Min height<input id="minHeight" value="${cs.minHeight}"></label></div><div class="subhead">Margin px</div><div class="grid2"><label>Top<input id="mt" type="number" value="${px(cs.marginTop)}"></label><label>Right<input id="mr" type="number" value="${px(cs.marginRight)}"></label><label>Bottom<input id="mb" type="number" value="${px(cs.marginBottom)}"></label><label>Left<input id="ml" type="number" value="${px(cs.marginLeft)}"></label></div><div class="subhead">Padding px</div><div class="grid2"><label>Top<input id="pt" type="number" value="${px(cs.paddingTop)}"></label><label>Right<input id="pr" type="number" value="${px(cs.paddingRight)}"></label><label>Bottom<input id="pb" type="number" value="${px(cs.paddingBottom)}"></label><label>Left<input id="pl" type="number" value="${px(cs.paddingLeft)}"></label></div>`;['width','height','maxWidth','minHeight'].forEach(id=>document.getElementById(id).onchange=e=>setStyle(id,e.target.value));[['mt','marginTop'],['mr','marginRight'],['mb','marginBottom'],['ml','marginLeft'],['pt','paddingTop'],['pr','paddingRight'],['pb','paddingBottom'],['pl','paddingLeft']].forEach(([id,p])=>bind(id,p,'px'))}
function imageInspector(){let el=selected.el;if(el.tagName!=='IMG'){el=el.querySelector?.('img');if(!el){inspector.innerHTML='<div class="empty">Δεν υπάρχει φωτογραφία σε αυτό το στοιχείο.</div>';return}selected={el,selector:selectorFor(el)};selectedBox.textContent=`IMG · ${selected.selector}`}const cs=iframe.contentWindow.getComputedStyle(el);inspector.innerHTML=`<div class="subhead">Αλλαγή φωτογραφίας</div><label>Από συσκευή<input id="imageFile" type="file" accept="image/*"></label><label>URL φωτογραφίας<input id="imageUrl" type="url" value="${el.getAttribute('src')||''}"></label><button id="useImageUrl">Χρήση URL</button><div class="subhead">Κάδρο</div><div class="grid2"><label>Object fit<select id="fit">${option('cover')}${option('contain')}${option('fill')}${option('none')}</select></label><label>Θέση<select id="position">${option('center center','Κέντρο')}${option('center top','Πάνω')}${option('center bottom','Κάτω')}${option('left center','Αριστερά')}${option('right center','Δεξιά')}</select></label><label>Brightness %<input id="brightness" type="number" min="0" max="250" value="100"></label><label>Contrast %<input id="contrast" type="number" min="0" max="250" value="100"></label><label>Saturation %<input id="saturation" type="number" min="0" max="300" value="100"></label><label>Grayscale %<input id="grayscale" type="number" min="0" max="100" value="0"></label></div>`;document.getElementById('fit').value=cs.objectFit||'cover';document.getElementById('position').value=cs.objectPosition||'center center';document.getElementById('fit').onchange=e=>setStyle('objectFit',e.target.value);document.getElementById('position').onchange=e=>setStyle('objectPosition',e.target.value);const updateFilter=()=>setStyle('filter',`brightness(${document.getElementById('brightness').value}%) contrast(${document.getElementById('contrast').value}%) saturate(${document.getElementById('saturation').value}%) grayscale(${document.getElementById('grayscale').value}%)`);['brightness','contrast','saturation','grayscale'].forEach(id=>document.getElementById(id).oninput=updateFilter);document.getElementById('useImageUrl').onclick=()=>{snapshot();const v=document.getElementById('imageUrl').value.trim();if(!v)return;el.src=v;ensureOverride(selected.selector).src=v;persist('Φωτογραφία live')};document.getElementById('imageFile').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{snapshot();el.src=r.result;ensureOverride(selected.selector).src=r.result;persist('Φωτογραφία live')};r.readAsDataURL(f)}}
function advancedInspector(){const cs=iframe.contentWindow.getComputedStyle(selected.el);inspector.innerHTML=`<div class="subhead">Advanced CSS</div><div class="grid2"><label>Display<select id="display">${['block','inline','inline-block','flex','grid','none'].map(v=>option(v)).join('')}</select></label><label>Position<select id="positionCss">${['static','relative','absolute','fixed','sticky'].map(v=>option(v)).join('')}</select></label><label>Z-index<input id="z" type="number" value="${cs.zIndex==='auto'?0:cs.zIndex}"></label><label>Overflow<select id="overflow">${['visible','hidden','auto','scroll'].map(v=>option(v)).join('')}</select></label></div><label>Transform<input id="transformCss" value="${cs.transform==='none'?'':cs.transform}" placeholder="scale(1) translateY(0px)"></label><label>Box shadow<input id="shadow" value="${cs.boxShadow==='none'?'':cs.boxShadow}" placeholder="0 20px 60px rgba(0,0,0,.3)"></label><p class="mini-note">Οι Advanced αλλαγές ισχύουν μόνο στο επιλεγμένο στοιχείο της συγκεκριμένης σελίδας.</p>`;document.getElementById('display').value=cs.display;document.getElementById('positionCss').value=cs.position;document.getElementById('overflow').value=cs.overflow;document.getElementById('display').onchange=e=>setStyle('display',e.target.value);document.getElementById('positionCss').onchange=e=>setStyle('position',e.target.value);bind('z','zIndex');document.getElementById('overflow').onchange=e=>setStyle('overflow',e.target.value);document.getElementById('transformCss').onchange=e=>setStyle('transform',e.target.value||'none');document.getElementById('shadow').onchange=e=>setStyle('boxShadow',e.target.value||'none')}
iframe.addEventListener('load',attachEditor);pagesUI();
document.querySelectorAll('[data-device]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-device]').forEach(x=>x.classList.remove('active'));b.classList.add('active');stage.className='preview-stage '+b.dataset.device});
document.getElementById('save').onclick=()=>persist('Αποθηκεύτηκε στον browser');
document.getElementById('undo').onclick=()=>{if(!history.length)return;state=JSON.parse(history.pop());persist('Αναίρεση');iframe.contentWindow.location.reload()};
document.getElementById('resetPage').onclick=()=>{if(!confirm('Reset όλων των αλλαγών αυτής της σελίδας;'))return;snapshot();delete state.pages[current];persist('Η σελίδα επανήλθε');iframe.contentWindow.location.reload()};
document.getElementById('export').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='athletico-admin-settings.json';a.click();URL.revokeObjectURL(a.href)};
document.getElementById('import').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{snapshot();state=JSON.parse(r.result);state.pages=state.pages||{};persist('Import ολοκληρώθηκε');iframe.contentWindow.location.reload()}catch{status.textContent='Μη έγκυρο JSON'}};r.readAsText(f)};
document.getElementById('pageBg').oninput=e=>{snapshot();pageState().page.background=e.target.value;iframe.contentDocument.body.style.setProperty('background',e.target.value,'important');persist('Φόντο σελίδας live')};
document.getElementById('pageColor').oninput=e=>{snapshot();pageState().page.color=e.target.value;iframe.contentDocument.body.style.setProperty('color',e.target.value,'important');persist('Χρώμα σελίδας live')};
document.getElementById('accentColor').oninput=e=>{snapshot();state.design.accent=e.target.value;iframe.contentDocument.documentElement.style.setProperty('--admin-accent',e.target.value);persist('Accent live')};
document.getElementById('contentWidth').oninput=e=>{snapshot();state.design.contentWidth=+e.target.value;persist('Πλάτος αποθηκεύτηκε')};